In [112]:
import pandas as pd
import numpy as np

In [113]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [114]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [115]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [116]:
movies=movies.merge(credits,on='title')

In [117]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [118]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [119]:
#Selected Columns
#genres
#id
#title
#keywords
#overview
#cast
#crew
movies=movies[['id','title','overview','genres','keywords','cast','crew']]

In [120]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [121]:
movies.isnull().sum()

id          0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [122]:
movies.dropna(inplace=True)

In [123]:
movies.isnull().sum()

id          0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [124]:
movies.duplicated().sum()

np.int64(0)

In [125]:
import ast
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [126]:
movies['genres']=movies['genres'].apply(convert)

In [127]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [128]:
movies['keywords']=movies['keywords'].apply(convert)

In [129]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [130]:
def convert3(obj):
    L=[]
    count=0
    for i in ast.literal_eval(obj):
        if count != 3:
            L.append(i['name'])
        else:
            break
    return L

In [131]:
movies['cast']=movies['cast'].apply(convert3)

In [132]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [133]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [134]:
movies['crew']=movies['crew'].apply(fetch_director)

In [135]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [136]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(' ','')for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(' ','')for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(' ','')for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(' ','')for i in x])

In [137]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [138]:
movies['overview']=movies['overview'].apply(lambda x:x.split())
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [139]:
movies.head()

,id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [140]:
new_df=movies[['id','title','tags']]
new_df

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [141]:
new_df['tags']=new_df['tags'].apply(lambda x:' '.join(x))

C:\Users\MC\AppData\Local\Temp\ipykernel_7288\218205508.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:' '.join(x))

In [142]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\MC\AppData\Local\Temp\ipykernel_7288\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [159]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\mc\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: click in c:\users\mc\anaconda3\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\mc\anaconda3\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\mc\anaconda3\lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\mc\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\mc\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [176]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [177]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [178]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\MC\AppData\Local\Temp\ipykernel_7288\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [179]:
new_df.head()

,id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [180]:
from sklearn.feature_extraction.text import CountVectorizer

In [181]:
cv=CountVectorizer(max_features=5000,stop_words='english')

In [182]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [183]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [184]:
features = cv.get_feature_names_out()
print(features.tolist())
print(features.shape)

['000', '007', '10', '100', '11', '12', '13', '14', '15', '16', '17', '18', '18th', '19', '1930', '1940', '1950', '1960', '1960s', '1970', '1970s', '1980', '1990', '19th', '19thcenturi', '20', '20th', '24', '25', '30', '3d', '40', '50', '60', '70', 'aaron', 'aaroneckhart', 'aarontaylor', 'aasifmandvi', 'abandon', 'abduct', 'abigailbreslin', 'abil', 'abl', 'abov', 'abus', 'academi', 'accept', 'access', 'accid', 'accident', 'accompani', 'accomplish', 'account', 'accus', 'ace', 'achiev', 'act', 'action', 'activ', 'activist', 'actor', 'actress', 'actual', 'adam', 'adambrodi', 'adamgoldberg', 'adamlefevr', 'adamsandl', 'adamscott', 'adamshankman', 'adapt', 'add', 'addict', 'adewaleakinnuoye', 'adjust', 'admir', 'admit', 'adolesc', 'adopt', 'ador', 'adrianmartinez', 'adrienbrodi', 'adult', 'adulteri', 'adulthood', 'advanc', 'adventur', 'adventure', 'advertis', 'advic', 'advis', 'affair', 'affect', 'afghanistan', 'africa', 'african', 'aftercreditssting', 'afterlif', 'aftermath', 'ag', 'agbaj', 'age', 'agediffer', 'agency', 'agenda', 'agent', 'aggress', 'ago', 'agre', 'ahead', 'aid', 'aidanquinn', 'ail', 'aim', 'air', 'airplan', 'airport', 'al', 'alanalda', 'alanarkin', 'alancum', 'alanrickman', 'alantudyk', 'alaska', 'albert', 'albertbrook', 'albertfinney', 'alcohol', 'alecbaldwin', 'alessandronivola', 'alex', 'alexandersiddig', 'alexapenavega', 'alexborstein', 'alexisbledel', 'alfredhitchcock', 'alfredmolina', 'alfrewoodard', 'ali', 'alic', 'alice', 'alicedrummond', 'aliciasilverston', 'aliciawitt', 'alien', 'alieninvas', 'alienlife', 'alilart', 'aliv', 'alive', 'allancordun', 'allen', 'allencovert', 'alleong', 'alli', 'allianc', 'allisonjanney', 'allow', 'alon', 'alongsid', 'alpacino', 'alreadi', 'alter', 'altern', 'alway', 'alzheimer', 'amanda', 'amandapeet', 'amandaseyfri', 'amateur', 'amaz', 'ambassador', 'amberheard', 'ambit', 'ambiti', 'ambul', 'ambush', 'america', 'american', 'americanfootbal', 'amid', 'amidst', 'amnesia', 'amp', 'amus', 'amusementpark', 'amyadam', 'amypoehl', 'amyryan', 'amysedari', 'amysmart', 'anagastey', 'analyst', 'anarchiccomedi', 'ancient', 'anderson', 'andi', 'andiemacdowel', 'andreamartin', 'andrebraugh', 'andrew', 'andrewdali', 'android', 'andydick', 'andygarcía', 'andyricht', 'andysamberg', 'andyserki', 'angel', 'angelabassett', 'angeles', 'angelinajoli', 'angelo', 'anger', 'angle', 'angri', 'angusmacinn', 'ani', 'anim', 'animalattack', 'animalhorror', 'animals', 'anjelicahuston', 'ann', 'anna', 'annafari', 'annakendrick', 'annalevin', 'annapaquin', 'annasophiarobb', 'anndowd', 'anne', 'annebancroft', 'annefletch', 'annehathaway', 'annehech', 'annemoss', 'annetteben', 'anni', 'annikaperga', 'announc', 'annual', 'anonym', 'anoth', 'answer', 'ant', 'antholog', 'anthoni', 'anthonyanderson', 'anthonyhopkin', 'anthonymacki', 'anthropomorph', 'anti', 'antihero', 'antonicoron', 'antoniobandera', 'antonyelchin', 'anyon', 'anyth', 'apart', 'apartheid', 'apartment', 'ape', 'apocalyps', 'apocalypt', 'appar', 'appear', 'appoint', 'appreci', 'apprentic', 'approach', 'april', 'arab', 'archaeologist', 'architect', 'arci', 'arctic', 'area', 'arena', 'argument', 'arielwint', 'arigraynor', 'aris', 'aristocrat', 'arm', 'armi', 'arminmueller', 'armor', 'armsdeal', 'armstrong', 'army', 'arnold', 'arnoldschwarzenegg', 'arrang', 'arrest', 'arriv', 'arrog', 'art', 'arthur', 'arthurj', 'arthurtovey', 'artificialintellig', 'artist', 'ash', 'ashley', 'ashleyjudd', 'ashtonkutch', 'asia', 'ask', 'aspir', 'assassin', 'assault', 'assign', 'assist', 'assistant', 'associ', 'assum', 'asteroid', 'astronaut', 'asylum', 'athlet', 'atomicbomb', 'attack', 'attempt', 'attend', 'attent', 'attitud', 'attorney', 'attract', 'audienc', 'audit', 'august', 'aunjanueelli', 'aunt', 'austin', 'australia', 'australian', 'author', 'autism', 'auto', 'avaacr', 'aveng', 'avoid', 'await', 'awaken', 'award', 'away', 'awkward', 'awri', 'awry', 'azizansari', 'babe', 'babi', 'baby', 'bachelor', 'backdrop', 'background', 'bad', 'bag', 'bahama', 'bail', 'bailey', 'balanc', 'ball', 'ballet', 'band', 'bandit', 'banish', 'bank', 'banker', 'bankrobberi', 'baptist', 'bar', 'barbarahershey', 'barbrastreisand', 'bare', 'bargain', 'barn', 'barney', 'baron', 'barri', 'barrylevinson', 'barrypepp', 'barryshabakahenley', 'bas', 'base', 'basebal', 'basedoncomicbook', 'basedongraphicnovel', 'basedonnovel', 'basedonplay', 'basedonstagemus', 'basedontrueev', 'basedontruestori', 'basedontvseri', 'basedonvideogam', 'basedonyoungadultnovel', 'basement', 'basketbal', 'batman', 'battl', 'battle', 'battlefield', 'bay', 'bdwong', 'beach', 'bear', 'beast', 'beat', 'beaubridg', 'beauti', 'beautiful', 'beautifulwoman', 'beauty', 'becam', 'becaus', 'beccasweitz', 'becom', 'becominganadult', 'bed', 'bedroom', 'beer', 'befor', 'befriend', 'began', 'begin', 'behavior', 'belief', 'believ', 'bell', 'bella', 'belong', 'belov', 'ben', 'benaffleck', 'benchaplin', 'bend', 'benedictcumberbatch', 'benedictwong', 'benfost', 'bengazzara', 'beniciodeltoro', 'benjamin', 'benjaminbratt', 'benkingsley', 'benmendelsohn', 'bennett', 'benstil', 'bent', 'benwhishaw', 'berlin', 'bernardhil', 'bernardle', 'berniemac', 'best', 'bestfriend', 'bet', 'beth', 'bethgrant', 'betray', 'bettemidl', 'better', 'betti', 'beverli', 'beverlyd', 'bibl', 'big', 'bigger', 'biggest', 'biker', 'bikini', 'billcamp', 'billcobb', 'billduk', 'billhad', 'billi', 'billionair', 'billmoseley', 'billmurray', 'billnighi', 'billnunn', 'billpaxton', 'billpullman', 'billybobthornton', 'billyburk', 'billyconnolli', 'billycrudup', 'billycryst', 'billydeewilliam', 'billyslaught', 'billywest', 'billyzan', 'biographi', 'bird', 'birth', 'birthday', 'bisexu', 'bishop', 'bit', 'bite', 'bitter', 'bizarr', 'black', 'blackmag', 'blackmail', 'blackpeopl', 'blade', 'blakeclark', 'blame', 'blend', 'blind', 'bliss', 'block', 'blond', 'blood', 'bloodi', 'bloodsplatt', 'bloodthirsti', 'blow', 'blue', 'blythedann', 'board', 'boardingschool', 'boat', 'bob', 'bobbalaban', 'bobbergen', 'bobbi', 'bobbycannaval', 'bobbyfarrelli', 'bobbymoynihan', 'bobclendenin', 'bobgunton', 'bobhoskin', 'bobodenkirk', 'bobstephenson', 'bodi', 'body', 'bodyguard', 'bokeemwoodbin', 'bold', 'bollywood', 'bomb', 'bond', 'bone', 'bonniehunt', 'book', 'border', 'bore', 'boredom', 'born', 'boss', 'boston', 'bound', 'bounti', 'bountyhunt', 'box', 'boxer', 'boy', 'boydbank', 'boydholbrook', 'boyfriend', 'boys', 'braddourif', 'bradgarrett', 'bradleycoop', 'bradleywhitford', 'bradpitt', 'bradwilliamhenk', 'brain', 'brand', 'brave', 'braveri', 'brazil', 'brazilian', 'break', 'breckinmey', 'brendanfras', 'brendangleeson', 'brendansextoniii', 'brentbrisco', 'brentspin', 'brettcullen', 'brettratn', 'brian', 'briancox', 'briandennehi', 'briandepalma', 'briandoyle', 'brianj', 'briano', 'bride', 'bridg', 'bridgettewilson', 'brief', 'brielarson', 'brien', 'brilliant', 'bring', 'brink', 'britain', 'british', 'britishsecretservic', 'brittanymurphi', 'broadway', 'broke', 'broken', 'brook', 'brooklyn', 'brothel', 'brother', 'brotherbrotherrelationship', 'brothers', 'brothersisterrelationship', 'brought', 'brown', 'bruce', 'brucecampbel', 'brucedern', 'brucegreenwood', 'brucemcgil', 'brucesp', 'brucewilli', 'brutal', 'bryan', 'bryancranston', 'bryansing', 'brycedallashoward', 'bu', 'buck', 'bud', 'buddi', 'buddycomedi', 'budget', 'build', 'building', 'built', 'bullet', 'bulli', 'bumbl', 'burglar', 'buri', 'burn', 'burtreynold', 'bush', 'busi', 'business', 'businessman', 'bust', 'butler', 'buy', 'byrn', 'cabin', 'cal', 'california', 'callumkeithrenni', 'calvin', 'came', 'camera', 'cameron', 'cameronbright', 'camerondiaz', 'camgigandet', 'camp', 'campaign', 'campbel', 'campu', 'canada', 'canadian', 'cancer', 'candid', 'cannib', 'capabl', 'capit', 'captain', 'captiv', 'captur', 'car', 'caraccid', 'caraseymour', 'carchas', 'carcrash', 'card', 'care', 'career', 'careymulligan', 'caribbean', 'carjourney', 'carl', 'carlagallo', 'carlagugino', 'carlo', 'carlosalazraqui', 'carmen', 'carmenelectra', 'carol', 'carolineaaron', 'carolinegoodal', 'carolkan', 'carrac', 'carri', 'carrie', 'carriefish', 'carter', 'cary', 'caryelw', 'case', 'caseyaffleck', 'cash', 'casino', 'cast', 'castl', 'cat', 'cataclysm', 'catastroph', 'catch', 'cateblanchett', 'catherinekeen', 'catherineo', 'catherinezeta', 'cathey', 'cathol', 'catholic', 'caught', 'caus', 'cave', 'cedrictheentertain', 'celebr', 'celiaimri', 'celiaweston', 'cellphon', 'cemeteri', 'center', 'central', 'centuri', 'century', 'certain', 'chadmichaelmurray', 'chain', 'chainsaw', 'challeng', 'champion', 'championship', 'chanc', 'chance', 'chancekelli', 'chang', 'channingtatum', 'chao', 'chaos', 'chapter', 'charact', 'character', 'characters', 'charg', 'charismat', 'charl', 'charlesd', 'charlesdurn', 'charlesnapi', 'charless', 'charli', 'charlie', 'charliesheen', 'charlizetheron', 'charlotterampl', 'charltonheston', 'charm', 'chase', 'chazzpalminteri', 'cheat', 'cheechmarin', 'cheerlead', 'chef', 'chelcieross', 'chemic', 'cher', 'chevychas', 'chicago', 'chicken', 'chief', 'child', 'childabus', 'childhood', 'children', 'chill', 'chimcbrid', 'china', 'chines', 'chip', 'chiwetelejiofor', 'chloëgracemoretz', 'chloësevigni', 'choic', 'choos', 'chosen', 'chri', 'chrisbrown', 'chriscolumbu', 'chriscoop', 'chriselli', 'chrisevan', 'chrishemsworth', 'chrisklein', 'chrismessina', 'chrismil', 'chriso', 'chrisparnel', 'chrispenn', 'chrispin', 'chrispratt', 'chrisrock', 'christ', 'christian', 'christianbal', 'christianslat', 'christinaappleg', 'christinaricci', 'christinebaranski', 'christma', 'christmas', 'christmasparti', 'christoph', 'christopherguest', 'christopherlambert', 'christopherle', 'christopherlloyd', 'christophermcdonald', 'christophermeloni', 'christophermintz', 'christopherplumm', 'christopherwalken', 'christophwaltz', 'chronicl', 'church', 'cia', 'ciaránhind', 'cillianmurphi', 'cinema', 'circl', 'circu', 'circumst', 'citi', 'citizen', 'city', 'civil', 'civilian', 'civilwar', 'claim', 'clair', 'clairedan', 'claireforlani', 'clan', 'clancybrown', 'clark', 'clarkgregg', 'clash', 'class', 'classic', 'classmat', 'classroom', 'claudevandamm', 'cleaduval', 'clean', 'clear', 'clerk', 'client', 'cliffcurti', 'cliftoncollinsjr', 'climat', 'climb', 'clinteastwood', 'clinthoward', 'cliveowen', 'clock', 'clone', 'clorisleachman', 'close', 'closer', 'clown', 'club', 'clue', 'coach', 'coast', 'cocain', 'code', 'codycameron', 'coffin', 'cohen', 'col', 'cold', 'coldwar', 'cole', 'colehaus', 'colinfarrel', 'colinfirth', 'colinhank', 'colinsalmon', 'collaps', 'colleagu', 'collect', 'collector', 'colleencamp', 'colleg', 'college', 'collid', 'collin', 'collis', 'colmfeor', 'colmmeaney', 'colonel', 'coloni', 'color', 'coma', 'combat', 'combin', 'come', 'comeback', 'comedi', 'comedian', 'comedy', 'comfort', 'comic', 'coming', 'comingofag', 'comingout', 'command', 'commando', 'commerci', 'commit', 'common', 'commun', 'compani', 'companion', 'company', 'compet', 'competit', 'competition', 'complet', 'complex', 'complic', 'compos', 'compton', 'comput', 'concern', 'concert', 'condit', 'confess', 'confid', 'conflict', 'confront', 'confus', 'congress', 'conman', 'connect', 'connel', 'connienielsen', 'connieray', 'connor', 'conquer', 'conradvernon', 'consequ', 'consequences', 'consid', 'conspir', 'conspiraci', 'constantli', 'construct', 'consum', 'contact', 'contain', 'contemporari', 'contend', 'contest', 'continu', 'contract', 'control', 'controversi', 'convent', 'convict', 'convinc', 'cook', 'cool', 'cooper', 'cop', 'cope', 'core', 'coreyburton', 'coreystol', 'corner', 'corpor', 'corps', 'corrupt', 'cost', 'costum', 'couldn', 'count', 'countri', 'country', 'countrysid', 'coup', 'coupl', 'couple', 'courag', 'cours', 'court', 'courtcas', 'courteneycox', 'courtroom', 'cousin', 'cover', 'covert', 'cowardli', 'cowboy', 'crack', 'craft', 'craig', 'craigrobinson', 'craigt', 'crash', 'crazi', 'creat', 'creation', 'creator', 'creatur', 'creatures', 'crew', 'crime', 'crimefight', 'crimin', 'criminals', 'crisi', 'crisis', 'crispinglov', 'critic', 'crocodil', 'crook', 'cross', 'crown', 'cruel', 'cruis', 'crusad', 'crush', 'crystal', 'crystallow', 'cuba', 'cubagoodingjr', 'cult', 'cultfilm', 'cultur', 'cultureclash', 'cup', 'cure', 'current', 'curs', 'curse', 'curtisarmstrong', 'custodi', 'custom', 'cut', 'cyberpunk', 'cyborg', 'cynic', 'dad', 'daili', 'dakotafan', 'daledickey', 'daledy', 'damag', 'dan', 'danaivey', 'danaykroyd', 'danc', 'dancer', 'danecook', 'danger', 'danhedaya', 'daniel', 'danielbrühl', 'danielcraig', 'danielday', 'danielmay', 'danielradcliff', 'danielroebuck', 'danielvonbargen', 'danni', 'danny', 'dannyaiello', 'dannydevito', 'dannyglov', 'dannyhuston', 'dannymann', 'dannymcbrid', 'dannytrejo', 'danpatrick', 'dare', 'dark', 'darkcomedi', 'darkest', 'darylhannah', 'darylsabara', 'dashmihok', 'date', 'daughter', 'dave', 'davechappel', 'davefoley', 'davefranco', 'davi', 'david', 'davidalangri', 'davidarquett', 'davidbow', 'davidbradley', 'davidcronenberg', 'davidcross', 'davidduchovni', 'davidfinch', 'davidharbour', 'davidhydepierc', 'davidjensen', 'davidkoechn', 'davidkrumholtz', 'davidmors', 'davido', 'davidogdensti', 'davidoyelowo', 'davidpaym', 'davidspad', 'davidstrathairn', 'davidthewli', 'davidwarn', 'davidwarshofski', 'davidwenham', 'daxshepard', 'day', 'days', 'dccomic', 'dea', 'dead', 'deadli', 'deaf', 'deal', 'dealer', 'dean', 'deannorri', 'death', 'deathofafriend', 'deathpenalti', 'debimazar', 'debramonk', 'debt', 'debut', 'decad', 'deceas', 'deceit', 'decept', 'decid', 'decis', 'declar', 'dedic', 'deed', 'deep', 'deeper', 'deepli', 'deeproy', 'defeat', 'defend', 'defens', 'defi', 'deirdreo', 'del', 'deliv', 'delroylindo', 'delus', 'demand', 'demimoor', 'demon', 'demonicpossess', 'demons', 'deniserichard', 'denisleari', 'deniso', 'denni', 'dennisdugan', 'dennisfarina', 'dennishaysbert', 'dennishopp', 'dennisquaid', 'dentist', 'denzelwashington', 'depart', 'depend', 'depict', 'depress', 'deputi', 'derang', 'deraydavi', 'derek', 'derekjacobi', 'derekluk', 'derekmear', 'dermotmulroney', 'descend', 'desert', 'design', 'desir', 'desmondllewelyn', 'desol', 'despair', 'desper', 'despit', 'destin', 'destini', 'destroy', 'destruct', 'destruction', 'detect', 'detective', 'determin', 'detroit', 'devast', 'develop', 'devic', 'devil', 'devis', 'devot', 'dexterfletch', 'diabol', 'dialogu', 'diamond', 'dianekeaton', 'dianekrug', 'dianelan', 'diannewiest', 'diari', 'dick', 'dickmil', 'dictat', 'did', 'didn', 'die', 'diedrichbad', 'diego', 'diegoluna', 'dies', 'differ', 'different', 'difficult', 'dig', 'dinamey', 'dinaspybey', 'diner', 'dinner', 'dinosaur', 'direct', 'director', 'dirti', 'dirtycop', 'disappear', 'disast', 'disaster', 'discov', 'discoveri', 'diseas', 'disease', 'disfigur', 'disgrac', 'disguis', 'disney', 'disord', 'dispatch', 'distant', 'district', 'disturb', 'dive', 'divid', 'divorc', 'divorce', 'djimonhouns', 'dna', 'doc', 'doctor', 'document', 'documentari', 'doe', 'doesn', 'dog', 'doll', 'dollar', 'dolphin', 'dolphlundgren', 'domhnallgleeson', 'domin', 'dominiccoop', 'dominicwest', 'don', 'donaldfaison', 'donaldsutherland', 'donallogu', 'doncheadl', 'donharvey', 'donnel', 'doom', 'door', 'dorsey', 'doubl', 'double', 'doublelif', 'doubt', 'doug', 'dougjon', 'douglasm', 'dr', 'dracula', 'drag', 'dragon', 'drama', 'dramat', 'draw', 'drawn', 'dread', 'dream', 'dreams', 'dress', 'drewbarrymor', 'drifter', 'drink', 'drive', 'driven', 'driver', 'drop', 'drown', 'drug', 'drugabus', 'drugaddict', 'drugdeal', 'druglord', 'drugs', 'drugtraff', 'drunk', 'drunken', 'du', 'dualident', 'dude', 'duel', 'duke', 'dump', 'duo', 'dure', 'duringcreditssting', 'dustinhoffman', 'dutch', 'duti', 'dutton', 'dwaynejohnson', 'dwightyoakam', 'dyinganddeath', 'dylan', 'dylanbak', 'dylanmcdermott', 'dynam', 'dysfunctionalfamili', 'dystopia', 'dystopicfutur', 'eager', 'earlbrown', 'earli', 'earlier', 'earn', 'earth', 'earthquak', 'easi', 'east', 'eat', 'eccentr', 'econom', 'economi', 'edbegleyjr', 'eddi', 'eddie', 'eddiegriffin', 'eddieizzard', 'eddiekayethoma', 'eddiemarsan', 'eddiemurphi', 'edg', 'edgarramírez', 'edharri', 'edhelm', 'ediemcclurg', 'editor', 'educ', 'edward', 'edwardburn', 'edwardherrmann', 'edwardjamesolmo', 'edwardnorton', 'effect', 'effort', 'egg', 'ego', 'egypt', 'el', 'eldenhenson', 'elderli', 'elect', 'eliaskotea', 'elijahwood', 'elimin', 'eliroth', 'elisabethshu', 'elit', 'eliwallach', 'elizabeth', 'elizabethbank', 'elizabethperkin', 'elizabethreas', 'ella', 'ellefan', 'ellenbarkin', 'ellenburstyn', 'ellenpag', 'elli', 'elliottgould', 'els', 'elud', 'elus', 'elv', 'elvi', 'embark', 'embethdavidtz', 'embroil', 'emerg', 'emigr', 'emilehirsch', 'emili', 'emilioestevez', 'emilyblunt', 'emilymortim', 'emilywatson', 'emma', 'emmarobert', 'emmaston', 'emmathompson', 'emmawatson', 'emmetwalsh', 'emot', 'emperor', 'empire', 'employ', 'employe', 'encount', 'encourag', 'end', 'enemi', 'enemies', 'enemy', 'energi', 'enforc', 'engag', 'engin', 'england', 'english', 'enigmat', 'enjoy', 'enlist', 'ensemblecast', 'ensu', 'ensues', 'entangl', 'enter', 'enterpris', 'entertain', 'entir', 'entiti', 'environment', 'epic', 'epidem', 'episod', 'equal', 'era', 'eric', 'ericbana', 'ericbogosian', 'ericidl', 'ericrobert', 'ericstoltz', 'erin', 'erniehudson', 'erotic', 'erupt', 'escap', 'escape', 'escort', 'especi', 'espionag', 'establish', 'estat', 'estrang', 'etern', 'ethan', 'ethanembri', 'ethanhawk', 'ethansuple', 'eugenelevi', 'europ', 'european', 'eva', 'evad', 'evamend', 'evanrachelwood', 'eve', 'event', 'events', 'eventu', 'everi', 'evermor', 'everybodi', 'everyday', 'everyon', 'everyth', 'evid', 'evil', 'evolv', 'ewanmcgregor', 'ewenbremn', 'ex', 'exact', 'exactli', 'examin', 'exchang', 'excit', 'execut', 'exist', 'existence', 'existenti', 'exorc', 'exot', 'exoticisland', 'expect', 'expected', 'expedit', 'experi', 'experienc', 'expert', 'explain', 'explod', 'exploit', 'explor', 'explos', 'expos', 'extramaritalaffair', 'extraordinari', 'extraterrestri', 'extraterrestrialtechnolog', 'extrem', 'extremeviol', 'eye', 'fac', 'face', 'fact', 'factori', 'fade', 'fail', 'fairi', 'fairytal', 'faith', 'faizonlov', 'fake', 'fall', 'fallen', 'fallinginlov', 'falseident', 'fame', 'famili', 'family', 'familyrelationship', 'famkejanssen', 'famou', 'fan', 'fangvamp', 'fantasi', 'fantast', 'fantasyworld', 'far', 'farm', 'farmer', 'fascin', 'fashion', 'fast', 'fat', 'fatal', 'fate', 'father', 'fatherdaughterrelationship', 'fathersonrelationship', 'favorit', 'fayedunaway', 'fbi', 'fbiagent', 'fear', 'fearsom', 'featur', 'feder', 'feel', 'feet', 'fellow', 'femal', 'female', 'femalefriendship', 'femalenud', 'femaleprotagonist', 'fend', 'ferguson', 'festiv', 'feud', 'fi', 'fiancé', 'fiction', 'fictionalplac', 'field', 'fierc', 'fight', 'fighter', 'figur', 'file', 'film', 'filmmak', 'filmproduc', 'films', 'final', 'financi', 'finish', 'firm', 'fish', 'fisherman', 'fishersteven', 'fistfight', 'fit', 'fix', 'flashback', 'flee', 'flesh', 'fli', 'flight', 'flirt', 'flood', 'florida', 'flower', 'flynn', 'focu', 'focus', 'foil', 'follow', 'food', 'foot', 'footag', 'footbal', 'footchas', 'forbidden', 'forbiddenlov', 'forc', 'force', 'forces', 'ford', 'foreign', 'forest', 'forestwhitak', 'forev', 'forever', 'forg', 'forget', 'forgiv', 'form', 'formid', 'formula', 'fort', 'fortun', 'fortune', 'forward', 'foster', 'fought', 'foundfootag', 'fourth', 'fox', 'frame', 'franc', 'france', 'francesdelatour', 'francesfish', 'francesmcdormand', 'francisco', 'francisfordcoppola', 'frank', 'frankenstein', 'frankgrillo', 'franki', 'frankiefaison', 'frankiemuniz', 'franklangella', 'frankoz', 'frankwelk', 'frankwhaley', 'frantic', 'fratern', 'fraud', 'freak', 'fred', 'fredarmisen', 'freddi', 'freddiehighmor', 'freddieprinzejr', 'fredtatascior', 'fredward', 'fredwillard', 'free', 'freedom', 'freeman', 'freez', 'french', 'fresh', 'freshman', 'friend', 'friendli', 'friends', 'friendship', 'frighten', 'frog', 'frontier', 'frustrat', 'fu', 'fuel', 'fugit', 'fulfil', 'fulli', 'fun', 'fund', 'funer', 'futur', 'future', 'futurist', 'ga', 

In [185]:
from sklearn.metrics.pairwise import cosine_similarity

In [186]:
similarity=cosine_similarity(vectors)

In [187]:
similarity

array([[1.        , 0.06818182, 0.07644708, ..., 0.04307305, 0.        ,
        0.        ],
       [0.06818182, 1.        , 0.07644708, ..., 0.02153652, 0.        ,
        0.02383656],
       [0.07644708, 0.07644708, 1.        , ..., 0.02414726, 0.        ,
        0.        ],
       ...,
       [0.04307305, 0.02153652, 0.02414726, ..., 1.        , 0.04307305,
        0.0451754 ],
       [0.        , 0.        , 0.        , ..., 0.04307305, 1.        ,
        0.09534626],
       [0.        , 0.02383656, 0.        , ..., 0.0451754 , 0.09534626,
        1.        ]], shape=(4806, 4806))

In [190]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [192]:
recommend('Batman Begins')

The Dark Knight
Batman
The Dark Knight Rises
Batman
Rockaway

In [197]:
import pickle

In [198]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [199]:
pickle.dump(similarity,open('similarity.pkl','wb'))